### ISSUE TITLE
Improvement for Player Demographics

### ISSUE THREAD

**Issue by Eyremba** [Rsl1122/Plan-Player-Demographics#1]
`        // Create lists
        String[] triggersA = {"i\\'m", "am", "im"};
        String[] femaleA = {"female", "girl", "gurl", "woman", "gal", "mrs", "she", "miss"};
        String[] maleA = {"male", "boy", "man", "boe", "sir", "mr", "guy", "he"};
        String[] ageA = {"years", "year-old", "old"};
        String[] ignoreA = {"sure", "think", "with", "are"};`

I could help you to add also support for the german language.

For triggersA add "bin"
For femaleA add "weiblich", "feminin", "mädchen", "frau"
For maleA add "männlich", "maskulin", "junge", "mann"
For ageA add "jahr", "jahre"

Also, someone could write something like "I'm 17".
Maybe you could catch such things to, just listen if the chat message starts with a trigger and ends directly with a number.

**Comment by Rsl1122** [comment]
Development of Player Demographics has been stopped because of integration to Plan.
I'll add the suggestion to Plan though.
